Updated to support the new Fyre infr node names
IBM/community-automation pull request #165
Opened 2021-06-06 17:44 UTC by IBMRob

Fyre has renamed the infra nodes to be fully qualified. This updates the automation to work with the new naming

2021-06-07 13:57 UTC, websterc87 requested changes
Would be nice for this to work with old and new fyre clusters.

It is ugly but

`shell: "echo api.$(hostname | grep api. | cut -f2 -d'.')$(hostname | grep -v api. | cut -f1 -d'.' | rev | cut -f1 -d'-' --complement | rev).cp.fyre.ibm.com"`

does the trick

2021-06-07 14:28 UTC, rayashworth commented
I also opened issue https://github.com/IBM/community-automation/pull/165

2021-06-07 14:36 UTC, rayashworth commented
@IBMRob can you update with the suggestion?

2021-06-07 14:43 UTC, IBMRob commented
@websterc87 - Can you confirm this has been tested and shown to work? I don't want to put it into my branch until it has because its being used by many teams to be unblocked and can't afford another break

2021-06-08 08:42 UTC, websterc87 approved these changes
Looks good

2021-06-08 13:31 UTC, merged